name: "LangLunches"
title: "LangLunches - Research Talks at UdS"
description: "Biweekly talks by PhDs and postdocs in the LST department at UdS"
baseurl: ""
url: "https://langlunches.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
