title: LangLunches
description: Biweekly talks by PhDs and postdocs in the LST department at UdS
baseurl: ""
url: "https://langlunches.github.io"

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author: "LST Department"
      share: false
      comments: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore 