title: LangLunches
description: Biweekly talks by PhDs and postdocs in the LST department at UdS
baseurl: "/aravind_website"
url: "https://learning-website-sample.github.io"

# Theme settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "default"

# Build settings
markdown: kramdown
permalink: pretty

# Include directories
include:
  - _pages
  - _layouts
  - _posts
  - _data
  - assets

# Default front matter
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "single"
      author: "LST Department"
      share: false
      comments: false
  -
    scope:
      path: "README.md"
    values:
      layout: "home"
      permalink: "/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore 