title: LangLunches
description: Biweekly talks by PhDs and postdocs in the LST department at UdS
baseurl: ""
url: "https://langlunches.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  pages:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore 